Repository UKHomeOffice/hocs-queue-tool, pull requests merged in 2022-12, with the labels that each got.

#69 HOCS-5996: migrate to profile queue activation
  .drone.yml
  README.md
  helm/hocs-queue-tool.yaml
  src/main/kotlin/uk/gov/digital/ho/hocs/queue/config/AwsConfiguration.kt
  src/main/kotlin/uk/gov/digital/ho/hocs/queue/config/AwsLocalStackConfiguration.kt
  src/main/kotlin/uk/gov/digital/ho/hocs/queue/config/helpers/QueueHelper.kt
  src/main/kotlin/uk/gov/digital/ho/hocs/queue/domain/enum/QueuePairName.kt
  src/main/resources/application-audit.yml
  src/main/resources/application-aws.yml
  src/main/resources/application-case-creator.yml
  src/main/resources/application-case-migrator.yml
  src/main/resources/application-document.yml
  src/main/resources/application-localstack.yml
  src/main/resources/application-notify.yml
  src/main/resources/application-search.yml
  src/main/resources/application.yml
  src/test/kotlin/uk/gov/digital/ho/hocs/queue/config/helpers/QueueHelperTest.kt
  src/test/kotlin/uk/gov/digital/ho/hocs/queue/service/AttributesQueueTest.kt
  src/test/kotlin/uk/gov/digital/ho/hocs/queue/service/BaseQueueHelper.kt
  src/test/kotlin/uk/gov/digital/ho/hocs/queue/service/PrintQueueTest.kt
  src/test/kotlin/uk/gov/digital/ho/hocs/queue/service/PurgeQueueTest.kt
  src/test/kotlin/uk/gov/digital/ho/hocs/queue/service/TransferQueueTest.kt
  src/test/resources/application-localstack.yml
  src/test/resources/application-migration.yml
Labels: major, smoketest

#71 HOCS-6015: rework purge endpoint for both queues
  README.md
  src/main/kotlin/uk/gov/digital/ho/hocs/queue/controller/QueueAdminController.kt
  src/main/kotlin/uk/gov/digital/ho/hocs/queue/service/QueueAdminService.kt
  src/test/kotlin/uk/gov/digital/ho/hocs/queue/service/PurgeQueueTest.kt
Labels: major

#73 HOCS-6014: add OpenSearch to default DEV queues
  helm/hocs-queue-tool.yaml
Labels: patch

#74 Chore: Update chart Major version
  .drone.yml
Labels: minor
